#普通数据的配置（注意冒号后有一个空格）
name: zhangsan

#对象的配置
server:
  port: 8082

person:
  name: zhangsan
  age: 18
  addr: beijing

#行内对象配置(使用较少)
#person: {name: zhangsan,age: 18,addr: beijing}

#配置数据：集合(普通字符串)
city:
  - beijing
  - tianjin
  - chongqing
  - shanghai

#city: [beijing, tianjin, chongqing, shanghai]

#配置数据：集合(对象数据)
student:
  - name: tom
    age: 18
    addr: beijing
  - name: lucy
    age: 20
    addr: chengdu

#student: [{name: tom,age: 18, addr: beijing},{name: lucy,age: 20, addr: chengdu}]

#Map配置
map:
  key1: value1
  key2: value2